name: Deploy to AWS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.5.0'
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Build dist
      run: npm run build:prod
      
    - name: Configure AWS Credentials
      if: success()
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2