name: Deploy to AWS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build dist
      run: npm run build:prod
      
    - name: Configure AWS Credentials
      if: success()
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://odzo-bikeshop