name: Trigger Sonarcloud analysis

on:
  push:
    branches:
    - dev/*
    
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=odzo
          -Dsonar.projectKey=bikeshop